// Auto-generated by tools/gen_hash.rs — DO NOT EDIT
//
// Code segment hash + developer signature
// IRAM 0x42060020, DRAM 0x3C060020
// Segment size: 426204 bytes
// Signed: false (signature must be regenerated with the release key)

/// SHA256 hash of the code segment
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static EXPECTED_FIRMWARE_HASH: [u8; 32] = [
    0x4f, 0xc2, 0xc6, 0x1f, 0xad, 0xd5, 0xa7, 0x86, 0x26, 0xdd, 0x49, 0x20, 0x06, 0x52, 0x96, 0x29, 0x4d, 0x9b, 0x7b, 0x57, 0x81, 0x02, 0xd0, 0xdf, 0xd1, 0x4c, 0xf4, 0xe4, 0x1b, 0x3b, 0xd0, 0x93
];

/// Schnorr signature of EXPECTED_FIRMWARE_HASH (signed by developer key)
/// All zeros only when no signing key was supplied
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static FIRMWARE_SIGNATURE: [u8; 64] = [0u8; 64];

/// Whether this build was signed with a developer key. Stored in rodata so the
/// generated value cannot be constant-folded into the executable being hashed.
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static FIRMWARE_SIGNED: bool = false;

/// Exact code segment size (from ESP-IDF binary header). Runtime-loaded from
/// rodata so convergence is independent of the generated value.
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static FIRMWARE_SIZE: usize = 426204;

/// Code segment address on instruction bus (IRAM). Runtime-loaded from rodata.
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static FIRMWARE_IADDR: u32 = 0x42060020;

