// KasKold — Air-gapped offline signing device for Kaspa
// Copyright (C) 2025-2026 KasSigner Project (kassigner@proton.me)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// KasKold — Firmware Hash Generator
// 100% Rust
//
// Parses the ESP-IDF binary generated by espflash, finds the code segment
// (load_addr = 0x4201_0020), and computes its SHA256.
//
// The hash must match EXACTLY what the bootloader computes
// when reading the same region from the data bus (0x3C01_0020).
//
// ESP-IDF binary format:
//   [0x00]       u8   magic (0xE9)
//   [0x01]       u8   segment_count
//   [0x02-0x03]  u16  SPI mode/speed
//   [0x04-0x07]  u32  entry_point
//   [0x08-0x17]  ...  more header fields
//   [0x18]       start of extended header (16 bytes)
//   [0x28]       start of segments
//
//   Each segment:
//     [+0x00] u32 load_addr   (virtual address where it loads)
//     [+0x04] u32 data_size   (size of segment data)
//     [+0x08] u8[data_size]   segment data
//
// We look for the segment with load_addr in the range 0x4200_0000..0x43FF_FFFF
// (flash mapped on instruction bus = code segment).
//
// IMPORTANT: The bootloader does not read the full segment — it scans until
// finding 16 consecutive 0xFFFFFFFF words. We replicate that logic
// here to hash exactly the same bytes.

use std::fs;

mod gen_hash {
    pub mod image;
    pub mod output;
}

use gen_hash::{image::{process_elf, process_esp_image, ESP_IMAGE_HEADER_SIZE, ESP_IMAGE_MAGIC, SEGMENT_HEADER_SIZE}, output::SigningIdentity};

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.len() < 2 || args.len() > 4 {
        eprintln!("Usage: gen-hash <firmware-binary> [signing-key-path] [production|development]");
        eprintln!("  firmware-binary: .bin file from espflash save-image");
        eprintln!("  signing-key-path: optional 32-byte BIP340 private scalar");
        eprintln!("  identity: production by default; development uses DEV_TEST_PUBKEY");
        eprintln!("  If no key is provided, signature will be all zeros (unsigned).");
        std::process::exit(1);
    }

    let firmware_path = &args[1];

    println!("  Firmware Segment Hash Generator");
    println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

    // ── Read the binary ─────────────────────────────────────────
    let firmware_data = match fs::read(firmware_path) {
        Ok(data) => data,
        Err(e) => {
            eprintln!("  Error leyendo firmware: {}", e);
            std::process::exit(1);
        }
    };

    println!("  File: {}", firmware_path);
    println!("  Total size: {} bytes ({} KB)", firmware_data.len(), firmware_data.len() / 1024);

    // ── Detect format ────────────────────────────────────────
    // Si es un ELF (empieza con 0x7F 'E' 'L' 'F'), necesitamos
    // convertirlo primero con espflash. Pero normalmente el build
    // script pasa el ELF y espflash lo convierte internamente.
    //
    // In our case, espflash flash generates a temporary .bin.
    // Pero nosotros recibimos el ELF. Necesitamos parsearlo como
    // ESP-IDF image — que es lo que espflash realmente flashea.
    //
    // SOLUTION: We use `espflash save-image` to generate the .bin,
    // o parseamos el ELF directamente buscando las secciones.
    //
    // For simplicity, first try to parse as ESP-IDF image.
    // If that fails (it is an ELF), try to parse ELF sections.

    let signing_key_path: Option<String> = if args.len() >= 3 { Some(args[2].clone()) } else { None };
    let signing_identity = match args.get(3).map(String::as_str).unwrap_or("production") {
        "production" => SigningIdentity::Production,
        "development" => SigningIdentity::Development,
        other => {
            eprintln!("  Invalid signing identity: {other}. Expected production or development.");
            std::process::exit(1);
        }
    };

    if firmware_data.len() < ESP_IMAGE_HEADER_SIZE + SEGMENT_HEADER_SIZE {
        eprintln!("  File too small to be a valid firmware");
        std::process::exit(1);
    }

    if firmware_data[0] == ESP_IMAGE_MAGIC {
        process_esp_image(&firmware_data, signing_key_path.as_deref(), signing_identity);
    } else if &firmware_data[0..4] == b"\x7fELF" {
        process_elf(&firmware_data, signing_key_path.as_deref(), signing_identity);
    } else {
        eprintln!("  Unrecognized format. Expected ESP-IDF image (0xE9) or ELF.");
        eprintln!("  First byte: 0x{:02X}", firmware_data[0]);
        eprintln!();
        eprintln!("  If passing an ELF, generate .bin first:");
        eprintln!("    espflash save-image --chip esp32s3 <ELF> firmware.bin");
        eprintln!("    gen-hash firmware.bin");
        std::process::exit(1);
    }
}
