// KasKold — Air-gapped offline signing device for Kaspa
// Copyright (C) 2025-2026 KasSigner Project (kassigner@proton.me)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// KasKold — Developer Signing Key Generator
// Generates a Schnorr keypair (secp256k1) for firmware signing.
//
// Usage: gen-keypair [output_dir]
//
// Creates:
//   dev_signing_key.bin  — 32-byte private key (KEEP SECRET, BACK UP OFFLINE)
//   production_release_pubkey.rs        — Rust const with public key (embed in firmware)
//
// The private key is used by gen_hash to sign firmware hashes at build time.
// The public key is embedded in the firmware and used at boot to verify signatures.
//
// WARNING: Losing the private key means you can NEVER sign firmware updates again.
//          Back it up to multiple secure offline locations.

use k256::{
    SecretKey,
    elliptic_curve::sec1::ToEncodedPoint,
};
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let output_dir = if args.len() > 1 { &args[1] } else { "." };

    println!("╔════════════════════════════════════════════════╗");
    println!("║  KasKold — Developer Signing Key Generator   ║");
    println!("╚════════════════════════════════════════════════╝");
    println!();

    let key_path = Path::new(output_dir).join("dev_signing_key.bin");
    let pubkey_rs_path = Path::new(output_dir).join("production_release_pubkey.rs");

    // Check if key already exists — refuse to overwrite
    if key_path.exists() {
        eprintln!("  ERROR: {} already exists!", key_path.display());
        eprintln!("  Refusing to overwrite existing signing key.");
        eprintln!("  Delete it manually if you really want to regenerate.");
        std::process::exit(1);
    }

    // Generate random private key
    let sk = SecretKey::random(&mut rand_core::OsRng);
    let sk_bytes = sk.to_bytes();

    // Derive public key (x-only, 32 bytes, BIP340-style)
    let pk_point = sk.public_key().to_projective();
    let pk_affine = k256::AffinePoint::from(pk_point);
    let encoded = pk_affine.to_encoded_point(true); // compressed: 02/03 || x
    let pk_x_bytes: [u8; 32] = {
        let mut buf = [0u8; 32];
        buf.copy_from_slice(&encoded.as_bytes()[1..33]);
        buf
    };

    // Save private key
    let mut key_file = fs::File::create(&key_path).expect("Failed to create key file");
    key_file.write_all(&sk_bytes).expect("Failed to write key");
    println!("  Private key saved: {}", key_path.display());
    println!("  !! BACK THIS UP TO MULTIPLE SECURE OFFLINE LOCATIONS !!");
    println!();

    // Generate Rust const for public key
    let pk_array: String = pk_x_bytes.iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ");

    let pk_hex: String = pk_x_bytes.iter()
        .map(|b| format!("{:02x}", b))
        .collect();

    let rust_code = format!(
r#"// KasKold Production Release Public Key
// Auto-generated by tools/gen_keypair — DO NOT EDIT
//
// This is the x-only Schnorr public key (secp256k1, 32 bytes).
// The firmware uses this to verify that the firmware hash was
// signed by the developer's private key at build time.
//
// Public key: {pk_hex}

/// Production release public key (x-only Schnorr, 32 bytes)
pub const PRODUCTION_RELEASE_PUBKEY: [u8; 32] = [
    {pk_array}
];
"#,
        pk_hex = pk_hex,
        pk_array = pk_array,
    );

    let mut rs_file = fs::File::create(&pubkey_rs_path).expect("Failed to create pubkey.rs");
    rs_file.write_all(rust_code.as_bytes()).expect("Failed to write pubkey.rs");

    println!("  Public key file: {}", pubkey_rs_path.display());
    println!("  Public key (hex): {}", pk_hex);
    println!();
    println!("  Next steps:");
    println!("    1. Copy production_release_pubkey.rs content into crates/kaskold-hardware-core/src/update/release.rs PRODUCTION_RELEASE_PUBKEY");
    println!("    2. Store dev_signing_key.bin in a SAFE OFFLINE location");
    println!("    3. Use tools/build/firmware/build_with_hash.sh to sign builds automatically");
    println!();
    println!("  WARNING: Losing dev_signing_key.bin = can NEVER sign updates again!");
}
