import { decodeHexPayloadIfMagic, downloadBytes, hasMagic, hexToBytes } from './vault_bytes.js';

export function installCovenantWorkflows(ctx) {
  const { $, api, parse, show, status, openScanner, stopCamera, renderHome } = ctx;
  let lastResponse = null;

  function clear() {
    lastResponse = null;
    try { api('kaskold_vault_covenant_cancel')(); } catch {}
    $('covenant-warning').classList.add('hidden');
    $('covenant-warning').textContent = '';
    $('covenant-result-qr').replaceChildren();
    $('covenant-result-hex').textContent = '';
    $('covenant-scan-reveal').classList.add('hidden');
  }

  function renderReview(review) {
    $('covenant-mode').textContent = review.mode;
    $('covenant-scheme').textContent = review.scheme;
    $('covenant-key-id').textContent = review.keyIdHex;
    $('covenant-pubkey').textContent = review.pubkeyHex;
    $('covenant-commitment').textContent = review.commitmentHex;
    $('covenant-script-hash').textContent = review.scriptHashHex;
    $('covenant-context').textContent = review.context;
    const opaque = review.mode === 'Opaque' || review.mode === 'BindOpaque';
    $('covenant-warning').textContent = opaque
      ? 'Opaque covenant request: the Vault cannot independently interpret the covenant semantics. Confirm only if the displayed binding, script hash, and host context match your intended protocol.'
      : '';
    $('covenant-warning').classList.toggle('hidden', !opaque);
    show('covenant-review');
  }

  function renderResponse(response) {
    lastResponse = response;
    $('covenant-result-title').textContent = response.kind === 'KeyInfo' ? 'Covenant Key' : 'Covenant Result';
    $('covenant-result-note').textContent = response.awaitingReveal
      ? 'Nonce commitment created. Scan the matching host reveal to finalize the anti-klepto signature.'
      : 'Return this authenticated response to the requesting host.';
    $('covenant-result-qr').innerHTML = response.svg;
    $('covenant-result-hex').textContent = response.payloadHex;
    $('covenant-scan-reveal').classList.toggle('hidden', !response.awaitingReveal);
    show('covenant-result');
  }

  function prepare(bytes) {
    try {
      stopCamera();
      renderReview(parse(api('kaskold_vault_covenant_prepare')(bytes)));
      status('Covenant request parsed inside the Vault. Review every field before confirming.');
    } catch (error) { status(String(error), true); }
  }

  function start() {
    clear();
    openScanner('Covenant Sign', 'Scan a KasKold covenant KeyInfo, Bind, Known, or Opaque request.', prepare, clear);
  }

  $('single-covenant').onclick = start;
  $('covenant-cancel').onclick = () => {
    clear();
    renderHome();
    status('Covenant request rejected.');
  };
  $('covenant-confirm').onclick = () => {
    try { renderResponse(parse(api('kaskold_vault_covenant_confirm')())); }
    catch (error) { status(String(error), true); }
  };
  $('covenant-scan-reveal').onclick = () => {
    openScanner('Covenant Host Reveal', 'Scan the reveal generated by the same host/session that supplied the commitment.', bytes => {
      try {
        stopCamera();
        renderResponse(parse(api('kaskold_vault_covenant_reveal')(bytes)));
        status('Covenant anti-klepto reveal verified and signature finalized.');
      } catch (error) { status(String(error), true); }
    }, clear);
  };
  $('covenant-save').onclick = () => {
    try {
      if (!lastResponse?.payloadHex) throw new Error('No covenant response is available to save.');
      downloadBytes(hexToBytes(lastResponse.payloadHex), `kaskold-covenant-${lastResponse.kind.toLowerCase()}.bin`);
      status('Covenant response saved.');
    } catch (error) { status(String(error), true); }
  };
  $('covenant-done').onclick = () => {
    clear();
    renderHome();
  };

  ctx.startCovenant = start;
  ctx.prepareCovenant = prepare;
  ctx.routeCovenantPayload = bytes => {
    const payload = decodeHexPayloadIfMagic(bytes, ['CVSG', 'CVRV']) || bytes;
    if (hasMagic(payload, 'CVSG')) { prepare(payload); return true; }
    if (hasMagic(payload, 'CVRV')) {
      try {
        stopCamera();
        renderResponse(parse(api('kaskold_vault_covenant_reveal')(payload)));
      } catch (error) { status(String(error), true); }
      return true;
    }
    return false;
  };
}
