//! Code-segment hashing, optional signing, and source emission.

use firmware_tools::{sign_firmware_hash, sign_test_firmware_hash};
use shared_signer::bytes::zeroize_bytes;
use sha2::{Digest, Sha256};
use std::{fs, io::Write, path::Path};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SigningIdentity {
    Production,
    Development,
}

// ─── Code segment hash ──────────────────────────────────────
//
// Hashes exactly seg_size bytes from the code segment.
// The bootloader will use FIRMWARE_SIZE (= seg_size) to read the same
// cantidad de bytes desde DRAM y calcular el mismo hash.

pub(super) fn hash_code_segment(file_data: &[u8], data_offset: usize, seg_size: usize, load_addr: u32, signing_key: Option<&str>, signing_identity: SigningIdentity) {
    println!();
    println!("  Hashing code segment:");
    println!("    Load addr:    0x{:08X}", load_addr);
    println!("    File offset:  0x{:05X}", data_offset);
    println!("    Segment size: {} bytes ({} KB)", seg_size, seg_size / 1024);

    if data_offset + seg_size > file_data.len() {
        eprintln!("  ERROR: Segment exceeds file size!");
        std::process::exit(1);
    }

    if seg_size == 0 {
        eprintln!("  ERROR: Zero-size segment!");
        std::process::exit(1);
    }

    let segment_data = &file_data[data_offset..data_offset + seg_size];

    // ── Calcular SHA256 ─────────────────────────────────────────
    let mut hasher = Sha256::new();
    hasher.update(segment_data);
    let hash = hasher.finalize();

    let hash_bytes: [u8; 32] = hash.clone().into();
    let hash_hex: String = hash.iter().map(|b| format!("{:02x}", b)).collect();
    let hash_short: String = hash.iter().take(8).map(|b| format!("{:02x}", b)).collect();

    println!();
    println!("  SHA256: {}", hash_hex);
    println!("  Short:  {}...", hash_short);

    // ── Sign the hash with developer key (if provided) ─────────
    let mut sig_bytes = [0u8; 64];
    let mut signed = false;

    if let Some(key_path) = signing_key {
        let mut key_data = match fs::read(key_path) {
            Ok(data) => data,
            Err(error) => {
                eprintln!("  ERROR reading signing key {}: {}", key_path, error);
                std::process::exit(1);
            }
        };
        if key_data.len() != 32 {
            let actual_length = key_data.len();
            zeroize_bytes(&mut key_data);
            eprintln!(
                "  ERROR: Signing key must be exactly 32 bytes, got {}",
                actual_length
            );
            std::process::exit(1);
        }

        let mut private_key = [0u8; 32];
        private_key.copy_from_slice(&key_data);
        zeroize_bytes(&mut key_data);

        let signature_result = match signing_identity {
            SigningIdentity::Production => sign_firmware_hash(&private_key, &hash_bytes),
            SigningIdentity::Development => sign_test_firmware_hash(&private_key, &hash_bytes),
        };
        zeroize_bytes(&mut private_key);

        match signature_result {
            Ok(signature) => {
                sig_bytes = signature;
                signed = true;
                let sig_hex: String = sig_bytes
                    .iter()
                    .take(8)
                    .map(|byte| format!("{:02x}", byte))
                    .collect();
                println!("  Signature: {}... (signed)", sig_hex);
            }
            Err(error) => {
                eprintln!("  ERROR signing hash: {}", error);
                std::process::exit(1);
            }
        }
    } else {
        println!("  Signature: (none — no signing key provided)");
    }

    // ── Generate firmware_hash.rs ────────────────────────────────
    let hash_array: String = hash.iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ");

    let sig_array: String = sig_bytes.iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ");

    let output_path = Path::new("apps/kaskold-hardware/src/firmware_hash.rs");
    let rust_code = format!(
r#"// Auto-generated by tools/gen_hash.rs — DO NOT EDIT
//
// Code segment hash + developer signature
// IRAM 0x{load_addr:08X}, DRAM 0x{dram_addr:08X}
// Segment size: {seg_size} bytes
// Signed: {signed}

/// SHA256 hash of the code segment
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static EXPECTED_FIRMWARE_HASH: [u8; 32] = [
    {hash_array}
];

/// Schnorr signature of EXPECTED_FIRMWARE_HASH (signed by developer key)
/// All zeros only when no signing key was supplied
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static FIRMWARE_SIGNATURE: [u8; 64] = [
    {sig_array}
];

/// Whether this build was signed with a developer key. Stored in rodata so the
/// generated value cannot be constant-folded into the executable being hashed.
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static FIRMWARE_SIGNED: bool = {signed};

/// Exact code segment size (from ESP-IDF binary header). Runtime-loaded from
/// rodata so convergence is independent of the generated value.
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static FIRMWARE_SIZE: usize = {seg_size};

/// Code segment address on instruction bus (IRAM). Runtime-loaded from rodata.
#[used]
#[link_section = ".rodata.kaskold_firmware_identity"]
pub static FIRMWARE_IADDR: u32 = 0x{load_addr:08X};
"#,
        load_addr = load_addr,
        seg_size = seg_size,
        dram_addr = load_addr - 0x4200_0000 + 0x3C00_0000,
        hash_array = hash_array,
        sig_array = sig_array,
        signed = signed,
    );

    let mut file = match fs::File::create(output_path) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("  Error creating {}: {}", output_path.display(), e);
            std::process::exit(1);
        }
    };

    if let Err(e) = file.write_all(rust_code.as_bytes()) {
        eprintln!("  Error writing: {}", e);
        std::process::exit(1);
    }

    println!();
    println!("  Saved to: {}", output_path.display());
    if signed {
        println!("  Status: SIGNED CANDIDATE (release gates still required)");
    } else {
        println!("  Status: UNSIGNED (development build)");
    }
    println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
}
