# Shared paths and shell helpers for QEMU setup/build/run facades.

QEMU_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../qemu" && pwd)"
ROOT_DIR="$(cd "${QEMU_SCRIPT_DIR}/../../.." && pwd)"
# shellcheck source=qa/config/toolchains.env
source "${ROOT_DIR}/qa/config/toolchains.env"
QEMU_STATE_DIR="${KASKOLD_QEMU_HOME:-${XDG_DATA_HOME:-${HOME}/.local/share}/kaskold/qemu}"
ESP_IDF_VERSION="$KASKOLD_ESP_IDF_VERSION"
MANAGED_IDF_PATH="${QEMU_STATE_DIR}/esp-idf-${ESP_IDF_VERSION}"

# shellcheck source=scripts/linux/lib/admin.sh
source "${ROOT_DIR}/scripts/linux/lib/admin.sh"

require_command() {
    command -v "$1" >/dev/null 2>&1 || {
        printf 'ERROR: required command not found after setup: %s\n' "$1" >&2
        return 127
    }
}

source_if_present() {
    local path="$1"
    [[ -r "${path}" ]] || return 0
    # User-local toolchain exports are generated by rustup/espup/ESP-IDF.
    # shellcheck disable=SC1090
    source "${path}"
}
